version: "3"

services:
  redis:
    image: redis:latest
    container_name: redis-cache
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --save 60 1 --loglevel warning
    environment:
      - TZ=Asia/Seoul

  elasticsearch:
    build:
      context: ./elasticsearch
      dockerfile: Dockerfile
    container_name: elasticsearch
    restart: always
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false # 로컬/연습용이므로 보안 인증 해제
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m" # 메모리 사용량 512MB로 제한
      - TZ=Asia/Seoul
    ports:
      - "9200:9200"
    volumes:
      - es_data:/usr/share/elasticsearch/data

  backend:
    build: ./backend
    container_name: spring-backend
    restart: always
    depends_on:
      - redis
      - elasticsearch
    entrypoint:
      ["./wait-for-it.sh", "elasticsearch", "9200", "java", "-jar", "app.jar"]
    environment:
      TZ: Asia/Seoul
      SPRING_DATASOURCE_URL: ${RDS_URL}
      SPRING_DATASOURCE_PASSWORD: ${RDS_PASSWORD}
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379
      SPRING_ELASTICSEARCH_URIS: http://elasticsearch:9200
      OCI_USER_ID: ${OCI_USER_ID}
      OCI_TENANCY_ID: ${OCI_TENANCY_ID}
      OCI_FINGERPRINT: ${OCI_FINGERPRINT}
      OCI_REGION: ${OCI_REGION}
      OCI_NAMESPACE: ${OCI_NAMESPACE}
      OCI_PRIVATE_KEY: ${OCI_PRIVATE_KEY}

    ports:
      - "8080:8080"

  frontend:
    build:
      context: ./nextFront
      dockerfile: Dockerfile
    container_name: next-frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "3000:3000"

  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/maintenance.html:/usr/share/nginx/html/maintenance.html
    depends_on:
      - frontend
      - backend

# Elasticsearch 데이터를 영구 저장하기 위한 볼륨 설정
volumes:
  es_data:
