version: "3"

services:
  db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: #MySQL 루트 비밀번호를 입력해주세요
      MYSQL_DATABASE: #생성할 데이터베이스 이름을 입력해주세요
      MYSQL_USER: #MySQL 사용자 이름을 입력해주세요
      MYSQL_PASSWORD: #MySQL 사용자 비밀번호를 입력해주세요
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql

  backend:
    build: ./backend
    container_name: spring-backend
    restart: always
    depends_on:
      - db
    environment:
      TZ: Asia/Seoul
      SPRING_DATASOURCE_URL: #MySQL 데이터베이스 URL을 입력해주세요 (예: jdbc:mysql://db:3306/your_database_name)
      SPRING_DATASOURCE_PASSWORD: #MySQL 사용자 비밀번호를 입력해주세요
      OCI_USER_ID: ${OCI_USER_ID} #OCI 관련 시크릿입니다
      OCI_TENANCY_ID: ${OCI_TENANCY_ID}
      OCI_FINGERPRINT: ${OCI_FINGERPRINT}
      OCI_REGION: ${OCI_REGION}
      OCI_NAMESPACE: ${OCI_NAMESPACE}
      OCI_PRIVATE_KEY: ${OCI_PRIVATE_KEY}
    ports:
      - "8080:8080"

  frontend:
    build:
      context: ./nextFront
      dockerfile: Dockerfile
    container_name: next-frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "3000:3000"

  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
      - backend
